version: '3.1'

services:
  db-mysql:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "--innodb-use-native-aio=0"
    container_name: db-mysql
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodeappdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - challengenet
networks:
  challengenet:
    name: challengenet